{{- $clustername := .Values.cluster.name }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  {{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
  {{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ $clustername }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  kubernetesVersion: v1.24.8+rke2r1
  agentEnvVars:
  - name: HTTP_PROXY
    value: "http://proxy.tir.bdr.de:7539/\r"
  - name: HTTPS_PROXY
    value: "http://proxy.tir.bdr.de:7539/\r"
  - name: NO_PROXY
    value: "127.0.0.0/8,10.0.0.0/8,cattle-system.svc,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.fdz-mgmt.tc,.bdr.de,.bdr.fdz,.prd.fdz.tir.budru.de,.nat.tc,.fdz.tir.bdr.de\r"
  rkeConfig:
    etcd:
      disableSnapshots: false
      s3:
        bucket: s3-fdz-prd-public
        {{- if .Values.s3CredentialSecretName }}
        cloudCredentialName: {{ .Values.s3CredentialSecretName }}
        {{- end }}
        cloudCredentialName: cattle-global-data:cc-sv4w6
        endpoint: s3.ext.local:9021
        endpointCA: |
          -----BEGIN CERTIFICATE-----
          MIIDvTCCAqWgAwIBAgIJAPlLpyEV6yatMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNV
          BAYTAkRFMR0wGwYDVQQKDBRCdW5kZXNkcnVja2VyZWkgR21iSDElMCMGA1UEAwwc
          QnVuZGVzZHJ1Y2tlcmVpIFJvb3QgQ0EgMjAxNTEnMCUGCSqGSIb3DQEJARYYaXQt
          Y21AYnVuZGVzZHJ1Y2tlcmVpLmRlMB4XDTE1MDkwOTExMDE0MVoXDTM5MDkwMzEx
          MDE0MVowfDELMAkGA1UEBhMCREUxHTAbBgNVBAoMFEJ1bmRlc2RydWNrZXJlaSBH
          bWJIMSUwIwYDVQQDDBxCdW5kZXNkcnVja2VyZWkgUm9vdCBDQSAyMDE1MScwJQYJ
          KoZIhvcNAQkBFhhpdC1jbUBidW5kZXNkcnVja2VyZWkuZGUwggEiMA0GCSqGSIb3
          DQEBAQUAA4IBDwAwggEKAoIBAQDKF6HDQcTGnnLQMY5kTfUoooWEQTpY6rXsdu7V
          XSHIRK027u9OdmkP1K2mZbX7Aob+kDYILrtMicTm8NZoOcu+5y2cqbQhimUCFehC
          PJpVUEV4k5JeLWMFFI7lh64yFnwoRy3N14GOfWiSkOFb+omUmlXHIuA74tfMQTbI
          n/q+cYzCbaP4VVCPIJxfaWlHbjClgJIkEsnldBv+LvtLaDlfSmoCZHF1TBEM0uIt
          qJ51+azYSO6NjYAiRVoG250OAJzRTPXKxLKOGPrQmS8vsAjeKhyYBKReKQjbnzlX
          Ge/amEQd7xH8AIDJzBAqLWWQeoAt6KAgpCfP7inMfsFJDp7/AgMBAAGjQjBAMA8G
          A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBTahS6xW37F
          5CV0akQYCWcH8k5sCDANBgkqhkiG9w0BAQsFAAOCAQEARRQFFu3c76mL5uRTHL/b
          /Vsx7hWvOqwgg3n99miLXd8olpYHrW9tIX5GArnrFNBuoBtMly1hXqgAhY/E2Z4p
          jzlrzYR7/JCyix6ookMfgLZqJury+qL1bUoYKlaNRUU385+Sv8ttIU9Jyccpv31m
          AeUBX6eFRTgnFpTRBz+C9MM/p5BxTub6tdtOes5xkN34J5jluTsWYJ0xlHhAFqI4
          C1Ha0+bkQIAjuhZs9MsokA7dYh4t4jqTU9JHIz71qixvUoYesREVynsMmWVtipob
          0u9EbNdgQilTyngwERzXB3sfaUaAsdKFj+6ZRJnm349vH7B9X0izwzsXZo5Ss61/
          FA==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFGTCCBAGgAwIBAgITXQAAAAcodpzF+dP/bAAAAAAABzANBgkqhkiG9w0BAQsF
          ADB8MQswCQYDVQQGEwJERTEdMBsGA1UECgwUQnVuZGVzZHJ1Y2tlcmVpIEdtYkgx
          JTAjBgNVBAMMHEJ1bmRlc2RydWNrZXJlaSBSb290IENBIDIwMTUxJzAlBgkqhkiG
          9w0BCQEWGGl0LWNtQGJ1bmRlc2RydWNrZXJlaS5kZTAeFw0xODA3MDUxMDI3MjRa
          Fw0zMDA3MDUxMDM3MjRaMH8xCzAJBgNVBAYTAkRFMR0wGwYDVQQKDBRCdW5kZXNk
          cnVja2VyZWkgR21iSDEoMCYGA1UEAwwfQnVuZGVzZHJ1Y2tlcmVpLVN1Yi1DQS0y
          MDE4LUVYVDEnMCUGCSqGSIb3DQEJARYYaXQtY21AYnVuZGVzZHJ1Y2tlcmVpLmRl
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA57I4l16fXMmjBnCNB6ag
          WKJtjuyIAo6A475GIdTbTtwrhx6pCwQIEgFgO+ca4ong3AL26vCXX1zmlXdHRUQx
          6xj5EOFbQcjGA/GeEEQ5fNCVMKLRi3BLvDPHp/6fc55EnJ1JACgFZ88Bf+dNwPMp
          pFSVClB++5UDUV9C7rrn4pWH9Wl1CeFw6/5BigZ1V84a2kG8JqY1gHojJXHNH2RR
          4Hvg4EQgkrxofXX4S4qQjwUwLiRMYDd5hrBKrAau+ihv3GTK0lJw2kAu6MqqMD/d
          xLbTmljnEaOUqQ3r44/J0kfivy6VCCaay0o2rrVXyvi79KIgy5FU5caggytJz+Lj
          IwIDAQABo4IBjzCCAYswEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
          AQYwHQYDVR0OBBYEFLJ9+g0UBmOWHDsmnrNzhAY1Siy4MB8GA1UdIwQYMBaAFNqF
          LrFbfsXkJXRqRBgJZwfyTmwIMIGEBgNVHR8EfTB7MHmgd6B1hjVodHRwOi8vY3Js
          L2NybC9CdW5kZXNkcnVja2VyZWklMjBSb290JTIwQ0ElMjAyMDE1LmNybIY8aHR0
          cDovL2NybC5iZHIuZGUvY3JsL0J1bmRlc2RydWNrZXJlaSUyMFJvb3QlMjBDQSUy
          MDIwMTUuY3JsMIGdBggrBgEFBQcBAQSBkDCBjTBBBggrBgEFBQcwAoY1aHR0cDov
          L2FpYS9haWEvQnVuZGVzZHJ1Y2tlcmVpJTIwUm9vdCUyMENBJTIwMjAxNS5jcnQw
          SAYIKwYBBQUHMAKGPGh0dHA6Ly9haWEuYmRyLmRlL2FpYS9CdW5kZXNkcnVja2Vy
          ZWklMjBSb290JTIwQ0ElMjAyMDE1LmNydDANBgkqhkiG9w0BAQsFAAOCAQEArAxb
          wEbWaoGbeZw680lXZrKvVBVkJq7+Zq0S01EU3qO8/Ami4ZN18poXIbfQX72VJMVa
          bgQl0YL/71vThs4FLGEsCq3Cndbi3eSkb1e4D7DW8wMygPBE5XhHPztbdYlslWDm
          oG4mN3guK4CsPAlhwXR78v5UnnxP1Jfr/LmGVwzGvzFJWXbVSYRAOHn+41wHibiD
          qM9qqwJxP1YU64CK+YG5CRaI+hV5fUD2ophojc7SBdGa4Bx3om8v+0UIkjj3+nvs
          wFVp2WCTcMHb4VWbwcszQVETdwnSchHb7YFSQdFVZub5VSZicgSEVmuvoA5Gb2KE
          +W20RlISTI5hU4YWZA==
          -----END CERTIFICATE-----
        folder: {{ $clustername }}-backups
        region: ""
        skipSSLVerify: true
      snapshotRetention: 56
      snapshotScheduleCron: 0 */3 * * *
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      workerRole: false
      quantity: 3
      name: {{ $clustername }}-master
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ $clustername }}-master
      paused: false
      displayName: {{ $clustername }}-master
    - controlPlaneRole: false
      etcdRole: false
      workerRole: true
      quantity: 2
      name: {{ $clustername }}-worker
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ $clustername }}-worker
      paused: false
      displayName: {{ $clustername }}-worker
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
